controller_manager:
    ros__parameters:
        update_rate: 1000  # Hz

        use_sim_time: true

        position_controller:
            type: position_controllers/JointGroupPositionController

        joint_state_broadcaster:
            type: joint_state_broadcaster/JointStateBroadcaster

        velocity_controller:
            type: velocity_controllers/JointGroupVelocityController
                    
        # position_controller:
        #     type: position_controllers/JointGroupPositionController

        # joint_trajectory_controller:
        #     type: joint_trajectory_controller/JointTrajectoryController

position_controller:
    ros__parameters:
        joints:
            - front_left_axle_joint
            - front_right_axle_joint
            - base_rotation_joint
            - leg1_2_joint
            - leg2_3_joint
            - leg3_4_joint
            - end_effector_joint
            - claw_top_joint
            - claw_bottom_joint
        interface_name: position
        command_interfaces:
            - position
        state_interfaces:
            - position
            - velocity

            
velocity_controller:
    ros__parameters:
        joints:
            - rear_left_wheel_joint
            - rear_right_wheel_joint
            - front_left_wheel_joint
            - front_right_wheel_joint
        interface_name: velocity
        command_interfaces:
            - velocity
        state_interfaces:
            - position
            - velocity

# joint_trajectory_controller:
#     ros__parameters:
#         joints:
#             - base_rotation_joint
#             - leg1_2_joint
#             - leg2_3_joint
#             - leg3_4_joint
#             - end_effector_joint
#             - claw_top_joint
#             - claw_bottom_joint
#         interface_name: position
#         command_interfaces:
#             - position
#         state_interfaces:
#             - position
#             - velocity

        

#PREVIOUS

# position_controller:
#     ros__parameters:
#         joints:
#             - front_left_link_joint
#             - front_right_link_joint
#         interface_name: position
#         command_interfaces:
#             - position
#         state_interfaces:
#             - position
#             - velocity


# velocity_controller:
#     ros__parameters:
#         joints:
#             - rear_left_diff_joint
#             - rear_right_diff_joint
#         interface_name: velocity
#         command_interfaces:
#             - velocity
#         state_interfaces:
#             - position
#             - velocity
#  velocity_controller:
#     ros__parameters:
#         joints:
#             - rear_left_diff_joint
#             - rear_right_diff_joint
#             - front_left_wheel_link
#             - front_right_wheel_link
#         interface_name: velocity
#         command_interfaces:
#             - velocity
#         state_interfaces:
#             - position
#             - velocity







#Recent 

# position_controller:
#     ros__parameters:
#         joints:
#             - front_left_axle_joint
#             - front_right_axle_joint
#             - base_rotation_joint
#             - leg1_2_joint
#             - leg2_3_joint
#             - leg3_4_joint
#             - end_effector_joint
#             - claw_top_joint
#             - claw_bottom_joint

#         interface_name: position
#         command_interfaces:
#             - position
#         state_interfaces:
#             - position
#             - velocity


# velocity_controller:
#     ros__parameters:
#         joints:
#             - rear_left_wheel_joint
#             - rear_right_wheel_joint
#             - front_left_wheel_joint
#             - front_right_wheel_joint
#         interface_name: velocity
#         command_interfaces:
#             - velocity
#         state_interfaces:
#             - position
#             - velocity